- hosts: app
  become: yes

  tasks:

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-venv
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: /home/webuser/app
        state: directory

    - name: Copy app code
      copy:
        src: .
        dest: /home/webuser/app/

    - name: Create virtual environment
      command: python3 -m venv /home/webuser/app/venv

    - name: Install flask in venv
      command: /home/webuser/app/venv/bin/pip install flask

    - name: Run app
      shell: |
        nohup /home/webuser/app/venv/bin/python /home/webuser/app/app.py &
